version: '3.6'
services:
  broker:
    build: broker
    ports:
      - 8083:8083
  auldfellas:
    build: auldfellas
    ports:
      - 8080:8080
    depends_on:
      - broker
  dodgygeezers:
    build: dodgygeezers
    ports:
      - 8082:8082
    depends_on:
      - broker
  girlsallowed:
    build: girlsallowed
    ports:
      - 8081:8081
    depends_on:
      - broker