version: '3.6'
services:
  activemq:
    container_name: activemq
    image: rmohr/activemq:latest
    ports:
      - 8161:8161
      - 61616:61616
  broker:
    build: broker
  auldfellas:
    build: auldfellas
    depends_on:
      - broker
  dodgygeezers:
    build: dodgygeezers
    depends_on:
      - broker
  girlsallowed:
    build: girlsallowed
    depends_on:
      - broker