# broker-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: girlsallowed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: girlsallowed
  template:
    metadata:
      labels:
        app: girlsallowed
    spec:
      containers:
      - name: girlsallowed
        image: girlsallowed:1.0
        ports:
        - containerPort: 8081